### PR TITLE
feat(sms): add cancel method

### PR DESCRIPTION
**Pull request by PxyUp**
Add Method to Cancel sending

### CODE REVIEW

**Comment by PxyUp** [comment]
@bviolier Good day, what is about that?

**Comment by marcelcorso** [comment]
Hey @PxyUp . Thanks for the PR!

How about we call that function "Delete" instead of "Cancel"? I think it's closer to meaning of the DELETE http method that the API uses to take the action.

**Comment by PxyUp** [comment]
> Hey @PxyUp . Thanks for the PR!
> 
> How about we call that function "Delete" instead of "Cancel"? I think it's closer to meaning of the DELETE http method that the API uses to take the action.

Hey, i am agree, but for when some one wanna use that method. Delete we can all entity(sms), but cancel not all of them. I think for understand more clear 'Cancel', because this action can be only on scheduled SMS

**Comment by marcelcorso** [comment]
true. It's arguable. 

So I went and looked to the clients in other languages and for example on the java and php it's called Delete. 

https://github.com/messagebird/php-rest-api/blob/f2af2b8e1d319600a4911ca7b7d699647d3a260f/examples/message-delete.php#L8

So Delete it is :-D

**Comment by marcelcorso** [comment]
thank you! 
I'll give it a run tomorrow.

**Comment by marcelcorso** [comment]
tested ✅

**Pull request merged**
