### PR TITLE
Fixing linter warnings

### PR DESCRIPTION
**Pull request by cooldarkdryplace**
Nothing important, just few issues that gometalinter reports.

1. Fixing declarations according to golint complains.
2. Renamed Id to ID according to Go standard.
3. Added godocs to exported structs.
4. Fixed formatted messages.
5. Added goreportcard.

### CODE REVIEW

**Comment by samwierema** [comment]
Thanks for the pull request @bilinguliar! Fantastic work.

The main thing I'm worried about is breaking backwards compatibility with the change from `Id` to `ID`. What are your opinions here @prep @marcelcorso?

**Comment by bilinguliar** [comment]
I understand your worries @samwierema. There are some examples with "Id" instead of "ID" in pretty popular Go libraries. Mongo driver for instance: https://godoc.org/labix.org/v2/mgo#Collection.FindId

If you still have possibility to apply fix - only few maniacally pedantic Go developers will smile somewhere in a darkness of cubicals. But if it is to late - this will cause pain for those users who do not vendor this dependency, so would be better not to break contract and just ignore this single commit.

**Comment by marcelcorso** [comment]
I think "Id" is bad and more important to fix than being backwards
compatible.


On Mar 8, 2017 8:12 AM, "Andrii Zakharov" <notifications@github.com> wrote:

I understand your worries @samwierema <https://github.com/samwierema>.
There are some examples with "Id" instead of "ID" in pretty popular Go
libraries. Mongo driver for instance: https://godoc.org/labix.org/
v2/mgo#Collection.FindId

If you still have possibility to apply fix - only few maniacally pedantic
Go developers will smile somewhere in a darkness of cubicals. But if it is
to late - this will cause pain for those users who do not vendor this
dependency, so would be better not to break contract and just ignore this
single commit.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/messagebird/go-rest-api/pull/8#issuecomment-284965364>,
or mute the thread

**Comment by prep** [comment]
Hey @bilinguliar, thanks for taking the time to do this! I've been meaning to do it myself, but never got around to it.

Your PR looks good. @samwierema made a good point about backward-compatibility, but I agree with @marcelcorso that I'd rather have this sorted. The `go get` tool will fetch from master, so we cannot hide behind the "just bump the major version" argument, but the `Id` to `ID` change is small enough that I don't think it'll disrupt our customers too much.

@bilinguliar, can I ask you to make 1 minor change? I'd like you to change your godoc comment to the `Balance` struct to `// Balance describes your balance information.`.

**Comment by bilinguliar** [comment]
@prep I have updated godoc for balance struct, thanks. 

Even you have short description for structures now - package lacks general description. Not sure how you handle and update you documentation, but there is an approach to use separate doc.go file - with some description and possibly a link to your maintained documentation on your web site.

godoc.org [reference](https://godoc.org/github.com/messagebird/go-rest-api)  still looks a little bit unhandy. Of course this better be done as a separate PR.

**Pull request merged**
